### ISSUE TITLE
lab4 command not working

### ISSUE THREAD

**Issue by TidyData** [openfaas/workshop#72]
At [lab4 - use-http-context---querystring--headers section](https://github.com/openfaas/workshop/blob/master/lab4.md#use-http-context---querystring--headers)  

* Deploy a function that prints environmental variables using a built-in BusyBox command:
```
$ faas-cli deploy --name env --fprocess="env" --image="functions/alpine:latest" --network=func_functions
```  

I tried various ways, unsure if I'm doing something wrong or where it is going wrong...

**Comment by TidyData** [comment]
figured another way  

```
$ faas-cli new --lang dockerfile env-function --prefix="my-container-location"
# replace line with ENV fprocess="cat" to
# ENV fprocess="env"
$ faas-cli build -f ./env-function.yml
$ faas-cli deploy -f ./env-function.yml
Deploying: env.
Function env already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://<redacted>/function/env

$ echo | faas-cli invoke env
GOOD RESULTS
```

**Comment by alexellis** [comment]
Thanks for logging an issue, we'll look into it.

Alex

**Comment by alexellis** [comment]
> I tried various ways, unsure if I'm doing something wrong or where it is going wrong...

What was the error you got? I tried this and it worked first time for me and for @rgee0 too.

**Comment by rgee0** [comment]
@TidyData can you provide further details on why you think it wasn't working, please?

I find this interesting: `Function env already exists, attempting rolling-update.`

Here's my output:
```
$ faas list
Function                      	Invocations    	Replicas
figlet                        	0              	1    
mquery                        	0              	1    
nodeinfo                      	0              	1    
$ faas-cli deploy --name env --fprocess="env" --image="functions/alpine:latest" --network=func_functions

Deployed. 200 OK.
URL: http://127.0.0.1:8080/function/env

$ echo "" | faas-cli invoke env --query workshop=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=12773b431132
fprocess=env
HOME=/root
Http_X_Forwarded_For=10.255.0.2:50302
Http_User_Agent=Go-http-client/1.1
Http_Accept_Encoding=gzip
Http_Content_Type=text/plain
Http_X_Call_Id=9dc05246-3fee-4c48-94fe-672f71fca138
Http_X_Start_Time=1539023073533008000
Http_Method=POST
Http_ContentLength=-1
Http_Query=workshop=1
Http_Path=/function/env
Http_Host=env:8080
```

**Comment by TidyData** [comment]
I was not getting an error, but it also was **also not making my url endpoint** /function/env either  

When I ran the command how the workshop specified all the other endpoints were listed and it attempted rolling-update but never made the env one...

```
username@compname:~/folder/folder/openfaas-faas$ faas-cli deploy --name env --fprocess="env" --image="functions/alpine:latest" --network=func_functions
Deploying: echoit.
Function echoit already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://<gateway-ip>:<gateway-port>/function/echoit

Deploying: wordcount.
Function wordcount already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://<gateway-ip>:<gateway-port>/function/wordcount

Deploying: base64.
Function base64 already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://<gateway-ip>:<gateway-port>/function/base64

Deploying: markdown.
Function markdown already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://<gateway-ip>:<gateway-port>/function/markdown

Deploying: hubstats.
Function hubstats already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://<gateway-ip>:<gateway-port>/function/hubstats

Deploying: nodeinfo.
Function nodeinfo already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://<gateway-ip>:<gateway-port>/function/nodeinfo
```  

I then attempted to manually make it in the `http://<gateway-ip>:<gateway-port>/ui/` interface and it would never go to "ready"

I then rebooted and still same symptoms, I suspected returning from the night's suspending-mode  might have impacted it, but with the same symptoms after rebooting I don't think that was the case.   

Ubuntu 16.04

In the interest of working through the workshop, I attempted an alternative way with success  
```
username@compname:~/folder/folder/openfaas-faas$ faas-cli new --lang dockerfile env-function --prefix="personal-registry"
# replace line with ENV fprocess="cat" to
# ENV fprocess="env"
username@compname:~/folder/folder/openfaas-faas$ faas-cli build -f ./env-function.yml
username@compname:~/folder/folder/openfaas-faas$ faas-cli deploy -f ./env-function.yml
```

That loaded it and I moved forward within the workshop.  Upon this issue conversation's response from you, I attempted the initial command again and believe I figured out the problem!

## Believe figured out what the issue was!
When not in the openfaas-faas folder/git-repo it works!  the faas-cli must default to some stack.yml even when specifying the fprocess information.  I remember the notes about `stack.yml` when not specifying the -f yaml file but **I assumed for the usage of this command that would not be loaded by default**  

***The below worked as expected when not in the openfaas-fass folder/git-repo***
```
username@compname:~$ faas-cli deploy --name env --fprocess="env" --image="functions/alpine:latest" --network=func_functions

Deployed. 200 OK.
URL: http://<gateway-ip>:<gateway-port>/function/env
```
***For the below, now at least I understand why it works but I would describe it as working.  Granted, not how I initially expected it would work, but probably how I told it too....***
```
username@compname:~/folder/folder/openfaas-faas$ faas-cli deploy --name env --fprocess="env" --image="functions/alpine:latest" --network=func_functions
Deploying: hubstats.
Function hubstats already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://<gateway-ip>:<gateway-port>/function/hubstats

Deploying: nodeinfo.
Function nodeinfo already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://<gateway-ip>:<gateway-port>/function/nodeinfo

Deploying: echoit.
Function echoit already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://<gateway-ip>:<gateway-port>/function/echoit

Deploying: wordcount.
Function wordcount already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://<gateway-ip>:<gateway-port>/function/wordcount

Deploying: base64.
Function base64 already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://<gateway-ip>:<gateway-port>/function/base64

Deploying: markdown.
Function markdown already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://<gateway-ip>:<gateway-port>/function/markdown
```  

`view ~/folder/folder/openfaas-faas/stack.yml`  
```
provider:
  name: faas
  gateway: http://<gateway-ip>:<gateway-port>  # can be a remote server

functions:
  # Pass a username as an argument to find how many images user has pushed to Docker Hub.
  hubstats:
    lang: dockerfile
    image: functions/hubstats:latest
    skip_build: true

  # Node.js gives OS info about the node (Host)
  nodeinfo:
    lang: dockerfile
    image: functions/nodeinfo:latest
    skip_build: true

  # Uses `cat` to echo back response, fastest function to execute.
  echoit:
    lang: dockerfile
    image: functions/alpine:latest
    fprocess: "cat"
    skip_build: true

  # Counts words in request with `wc` utility
  wordcount:
    lang: dockerfile
    image: functions/alpine:latest
    fprocess: "wc"
    skip_build: true

  # Calculates base64 representation of request body.
  base64:
    lang: dockerfile
    image: functions/alpine:latest
    fprocess: "base64"
    skip_build: true

  # Converts body in (markdown format) -> (html)
  markdown:
    lang: dockerfile
    image: functions/markdown-render:latest
    skip_build: true
```  

I guess i discovered why the tutorial directs making lab subfolders...  

**My love of explicitness cannot be understated** and it seems explicitly declaring no yml file usage, at least for this tutorial, may be a good choice moving forward.

* [ ] I'll look into how that can be achieved using the `faas-cli deploy` command.  

Appreciate your time in even responding to my problem.  Totally impressed with openfaas and greatly enjoying this workshop.  Thank you!
